name: Reusable
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: name of deploy artifact
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs. artifact-name }}
      - name: list files
        run: ls
      - name: Output info
        run: echo "deploy and upload"